import Foundation

/// Renders a manifest as a human-readable Markdown report, written next to the
/// JSON manifest at every destination. Anyone handed the drive can open it
/// without our app. Failures are loud and near the top; a green verdict
/// appears only when every item verified at every destination.
public enum MarkdownReportWriter {
    public static func markdown(for manifest: TransferManifest) -> String {
        var lines: [String] = []

        lines.append("# \(text("Doppelganger Transfer Report"))")
        lines.append("")
        lines.append(verdictLine(for: manifest))
        lines.append("")
        lines.append("| | |")
        lines.append("|---|---|")
        lines.append("| \(text("Transfer")) | `\(manifest.transferID)` |")
        lines.append("| \(text("Source")) | `\(escape(manifest.sourceRoot))` |")
        for (index, destination) in manifest.destinations.enumerated() {
            lines.append("| \(format("Destination %lld", Int64(index + 1))) | `\(escape(destination.path))` — \(destinationSummary(destination)) |")
        }
        lines.append("| \(text("Started")) | \(manifest.startedAt) |")
        lines.append("| \(text("Finished")) | \(manifest.finishedAt) |")
        lines.append("| \(text("Files")) | \(manifest.summary.itemCount) (\(byteString(manifest.summary.totalBytes))) |")
        lines.append("| \(text("Checksum")) | \(manifest.algorithm) |")
        if let verificationProfile = manifest.verificationProfile {
            lines.append("| \(text("Verification profile")) | \(verificationProfile) |")
        }
        if let operatorName = manifest.operatorDisplayName {
            lines.append("| \(text("Operator")) | \(escape(operatorName)) |")
        }
        lines.append("")

        if let issues = manifest.issues, !issues.isEmpty {
            lines.append("## ⚠️ \(text("Transfer issues"))")
            lines.append("")
            for issue in issues { lines.append("- \(escape(issue))") }
            lines.append("")
        }

        let problems = problemRows(in: manifest)
        if !problems.isEmpty {
            lines.append("## ⚠️ \(format("Problems — %lld file/destination pair(s) did NOT verify", Int64(problems.count)))")
            lines.append("")
            lines.append("| \(text("File")) | \(text("Destination")) | \(text("Status")) | \(text("Reason")) |")
            lines.append("|---|---|---|---|")
            lines.append(contentsOf: problems)
            lines.append("")
        }

        lines.append("## \(text("Files"))")
        lines.append("")
        var header = "| \(text("File")) | \(text("Size")) | \(manifest.algorithm) |"
        var divider = "|---|---|---|"
        for index in manifest.destinations.indices {
            header += " \(format("Destination %lld", Int64(index + 1))) |"
            divider += "---|"
        }
        lines.append(header)
        lines.append(divider)
        for item in manifest.items {
            var row = "| `\(escape(item.relativePath))` | \(byteString(item.size)) | `\(item.digest ?? "—")` |"
            for result in item.results {
                row += " \(statusCell(result)) |"
            }
            lines.append(row)
        }
        lines.append("")
        lines.append("---")
        lines.append("*" + text("Generated by doppelganger. The JSON manifest alongside this file (`doppelganger-manifest-….json`) is the machine-verifiable record.") + "*")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    private static func verdictLine(for manifest: TransferManifest) -> String {
        switch manifest.status {
        case "transferredPendingVerification":
            text("**Result: 🟡 TRANSFERRED — VERIFICATION PENDING** — bytes were copied, but an independent destination read-back is still required. **Do not erase the source media.**")
        case "verified":
            text("**Result: ✅ VERIFIED** — every file passed checksum verification at every destination.")
        case "cancelled":
            text("**Result: ⛔️ CANCELLED** — this transfer was stopped before completion. **Do not treat these copies as complete.**")
        default:
            text("**Result: ❌ FAILED** — one or more files did **not** verify. **Do not erase the source media.**")
        }
    }

    private static func destinationSummary(_ destination: TransferManifest.DestinationRecord) -> String {
        var parts = [format("%lld verified", Int64(destination.verifiedCount))]
        if let pending = destination.pendingVerificationCount, pending > 0 {
            parts.append(format("%lld pending verification", Int64(pending)))
        }
        if destination.failedCount > 0 {
            parts.append(format("%lld failed", Int64(destination.failedCount)))
        }
        if destination.skippedCount > 0 {
            parts.append(format("%lld skipped", Int64(destination.skippedCount)))
        }
        return parts.joined(separator: ", ")
    }

    private static func problemRows(in manifest: TransferManifest) -> [String] {
        var rows: [String] = []
        for item in manifest.items {
            for result in item.results where result.status != "verified" {
                let reason = [result.reason, result.detail].compactMap(\.self).joined(separator: ": ")
                rows.append("| `\(escape(item.relativePath))` | `\(escape(result.destination))` | \(result.status) | \(escape(reason)) |")
            }
        }
        return rows
    }

    private static func statusCell(_ result: TransferManifest.ItemRecord.Result) -> String {
        switch result.status {
        case "verified": "✅ \(text("verified"))"
        case "transferred-pending-verification": "🟡 \(text("verification pending"))"
        case "failed": "❌ \(result.reason ?? text("failed"))"
        default: "⏭️ \(result.reason ?? text("skipped"))"
        }
    }

    private static func text(_ key: String) -> String {
        NSLocalizedString(key, tableName: nil, bundle: .main, value: key, comment: "Evidence report")
    }

    private static func format(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), locale: Locale.current, arguments: arguments)
    }

    private static func escape(_ text: String) -> String {
        text.replacingOccurrences(of: "|", with: "\\|")
    }

    /// Locale-independent decimal byte formatting, so reports are stable.
    static func byteString(_ bytes: Int64) -> String {
        let units = ["B", "KB", "MB", "GB", "TB", "PB"]
        var value = Double(bytes)
        var unit = 0
        while value >= 1000, unit < units.count - 1 {
            value /= 1000
            unit += 1
        }
        if unit == 0 {
            return "\(bytes) B"
        }
        let rounded = (value * 100).rounded() / 100
        return "\(rounded) \(units[unit])"
    }
}
