/// Renders a manifest as a human-readable Markdown report, written next to the
/// JSON manifest at every destination. Anyone handed the drive can open it
/// without our app. Failures are loud and near the top; a green verdict
/// appears only when every item verified at every destination.
public enum MarkdownReportWriter {
    public static func markdown(for manifest: TransferManifest) -> String {
        var lines: [String] = []

        lines.append("# Doppelganger Transfer Report")
        lines.append("")
        lines.append(verdictLine(for: manifest))
        lines.append("")
        lines.append("| | |")
        lines.append("|---|---|")
        lines.append("| Transfer | `\(manifest.transferID)` |")
        lines.append("| Source | `\(escape(manifest.sourceRoot))` |")
        for (index, destination) in manifest.destinations.enumerated() {
            lines.append("| Destination \(index + 1) | `\(escape(destination.path))` — \(destinationSummary(destination)) |")
        }
        lines.append("| Started | \(manifest.startedAt) |")
        lines.append("| Finished | \(manifest.finishedAt) |")
        lines.append("| Files | \(manifest.summary.itemCount) (\(byteString(manifest.summary.totalBytes))) |")
        lines.append("| Checksum | \(manifest.algorithm) |")
        lines.append("")

        if let issues = manifest.issues, !issues.isEmpty {
            lines.append("## ⚠️ Transfer issues")
            lines.append("")
            for issue in issues { lines.append("- \(escape(issue))") }
            lines.append("")
        }

        let problems = problemRows(in: manifest)
        if !problems.isEmpty {
            lines.append("## ⚠️ Problems — \(problems.count) file/destination pair(s) did NOT verify")
            lines.append("")
            lines.append("| File | Destination | Status | Reason |")
            lines.append("|---|---|---|---|")
            lines.append(contentsOf: problems)
            lines.append("")
        }

        lines.append("## Files")
        lines.append("")
        var header = "| File | Size | \(manifest.algorithm) |"
        var divider = "|---|---|---|"
        for index in manifest.destinations.indices {
            header += " Destination \(index + 1) |"
            divider += "---|"
        }
        lines.append(header)
        lines.append(divider)
        for item in manifest.items {
            var row = "| `\(escape(item.relativePath))` | \(byteString(item.size)) | `\(item.digest ?? "—")` |"
            for result in item.results {
                row += " \(statusCell(result)) |"
            }
            lines.append(row)
        }
        lines.append("")
        lines.append("---")
        lines.append("*Generated by doppelganger. The JSON manifest alongside this file " +
                     "(`doppelganger-manifest-….json`) is the machine-verifiable record.*")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    private static func verdictLine(for manifest: TransferManifest) -> String {
        switch manifest.status {
        case "verified":
            "**Result: ✅ VERIFIED** — every file passed checksum verification at every destination."
        case "cancelled":
            "**Result: ⛔️ CANCELLED** — this transfer was stopped before completion. " +
            "**Do not treat these copies as complete.**"
        default:
            "**Result: ❌ FAILED** — one or more files did **not** verify. " +
            "**Do not erase the source media.**"
        }
    }

    private static func destinationSummary(_ destination: TransferManifest.DestinationRecord) -> String {
        var parts = ["\(destination.verifiedCount) verified"]
        if destination.failedCount > 0 { parts.append("\(destination.failedCount) failed") }
        if destination.skippedCount > 0 { parts.append("\(destination.skippedCount) skipped") }
        return parts.joined(separator: ", ")
    }

    private static func problemRows(in manifest: TransferManifest) -> [String] {
        var rows: [String] = []
        for item in manifest.items {
            for result in item.results where result.status != "verified" {
                let reason = [result.reason, result.detail].compactMap(\.self).joined(separator: ": ")
                rows.append("| `\(escape(item.relativePath))` | `\(escape(result.destination))` | \(result.status) | \(escape(reason)) |")
            }
        }
        return rows
    }

    private static func statusCell(_ result: TransferManifest.ItemRecord.Result) -> String {
        switch result.status {
        case "verified": "✅ verified"
        case "failed": "❌ \(result.reason ?? "failed")"
        default: "⏭️ \(result.reason ?? "skipped")"
        }
    }

    private static func escape(_ text: String) -> String {
        text.replacingOccurrences(of: "|", with: "\\|")
    }

    /// Locale-independent decimal byte formatting, so reports are stable.
    static func byteString(_ bytes: Int64) -> String {
        let units = ["B", "KB", "MB", "GB", "TB", "PB"]
        var value = Double(bytes)
        var unit = 0
        while value >= 1000, unit < units.count - 1 {
            value /= 1000
            unit += 1
        }
        if unit == 0 {
            return "\(bytes) B"
        }
        let rounded = (value * 100).rounded() / 100
        return "\(rounded) \(units[unit])"
    }
}
